#!/bin/bash

meta() {
  echo '# mackerel-agent-plugin'
  cat <<EOS
{
  "graphs": {
    "smart.temperature": {
      "label": "S.M.A.R.T. Temperatures",
      "unit": "integer",
      "metrics": [
        {
          "name": "#",
          "label": "Temperature",
          "stacked": false
        }
      ]
    }
  }
}
EOS
}

metrics() {
  local time=$(date +"%s")

  if [ -n "$(ls /dev/sd? 2>/dev/null)" ]; then
    for device in $(ls /dev/sd? |  sed 's/\/dev\///'); do
      local value=$(smartctl -A "/dev/${device}" 2>/dev/null | grep Temperature | head -n 1 | awk '{print $10}')
      if [ -n "$value" ]; then
        echo -e "smart.temperature.${device}\t${value}\t${time}"
      fi
    done
  fi

  if [ -n "$(ls /dev/nvme? 2>/dev/null)" ]; then
    for device in $(ls /dev/nvme? |  sed 's/\/dev\///'); do
      local value=$(smartctl -A "/dev/${device}" 2>/dev/null | grep Temperature | head -n 1 | awk '{print $2}')
      if [ -n "$value" ]; then
        echo -e "smart.temperature.${device}\t${value}\t${time}"
      fi
    done
  fi
}

if [ -n "${MACKEREL_AGENT_PLUGIN_META}" ]; then
  meta
else
  metrics
fi
